GET http://localhost:5134/foods

###
POST http://localhost:5134/foods
Content-Type: application/json

{
  "name": "Jollof Rice",
  "description": "Spicy Ghanaian rice dish",
  "price": 25.50,
  "imageUrl": "https://example.com/jollof.jpg",
  "categoryId": 1
}